// <auto-generated />
using Fiction.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fiction.Migrations
{
    [DbContext(typeof(FictionDbContext))]
    [Migration("20210325204010_added new items")]
    partial class addednewitems
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fiction.Models.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoryId");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 21,
                            Name = "Test",
                            StoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            Age = 22,
                            Name = "Frodo",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            Age = 42,
                            Name = "Joel",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 4,
                            Age = 32,
                            Name = "Sara",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 5,
                            Age = 22,
                            Name = "PotM",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 6,
                            Age = 62,
                            Name = "Warden",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 7,
                            Age = 22,
                            Name = "Naga",
                            StoryId = 2
                        },
                        new
                        {
                            Id = 8,
                            Age = 12,
                            Name = "Harry",
                            StoryId = 3
                        });
                });

            modelBuilder.Entity("Fiction.Models.Story", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Some great story"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Awesome story with unexpected ending"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Great news about that story"
                        });
                });

            modelBuilder.Entity("Fiction.Models.Character", b =>
                {
                    b.HasOne("Fiction.Models.Story", "Story")
                        .WithMany("Character")
                        .HasForeignKey("StoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Story");
                });

            modelBuilder.Entity("Fiction.Models.Story", b =>
                {
                    b.Navigation("Character");
                });
#pragma warning restore 612, 618
        }
    }
}
